trigger:
- main

pool:
  name: PierrePool

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run tests with pytest'

# Assuming your scripts generate artifacts in a folder named 'artifacts'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts' # Update this to the path where your artifacts are located
    ArtifactName: 'myArtifacts' # Name of the artifact
    publishLocation: 'Container'
